# Generated by Django 3.2 on 2023-01-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='map',
            field=models.TextField(default=999),
            preserve_default=False,
        ),
    ]
